pipeline:
- op: CustomClean
  target: train
  params:
    rules:
    - col: EDUCATION
      eq: 0
    - col: EDUCATION
      eq: 5
    - col: EDUCATION
      eq: 6
    - col: MARRIAGE
      eq: 0
    mode: map_values
- op: CreateFeature
  target: train
  params:
    source_cols:
    - LIMIT_BAL
    - AGE
    output_col: LIMIT_PER_AGE
    method: ratio
- op: TransformPower
  target: train
  params:
    cols:
    - LIMIT_BAL
    output_cols:
    - LIMIT_LOG
    method: log
- op: JoinTable
  target: train
  params:
    aux_df: $monthly_history
    key_col: ID
    prefix: PANEL
    max_cols: 30
    method: agg
- op: CustomProcess
  target: train
  params:
    threshold: 0.7
    mode: drop_high_null
- op: OneHotEncode
  target: train
  params:
    cols:
    - EDUCATION
    - MARRIAGE
    max_cardinality: 8
- op: LabelEncode
  target: train
- op: HandleMV
  target: train
  params:
    cols:
    - LIMIT_BAL
    - AGE
    - LIMIT_PER_AGE
    - LIMIT_LOG
    n_neighbors: 5
    method: knn
- op: HandleMV
  target: train
  params:
    method: median
- op: ReduceDimension
  target: train
  params:
    cols:
    - LIMIT_BAL
    - AGE
    - LIMIT_PER_AGE
    - LIMIT_LOG
    target_col: $target_col
    n_components: 1
    method: lda
- op: SelectFeature
  target: train
  params:
    target_col: $target_col
    n_features_to_select: 15
    estimator: tree
    exclude_cols:
    - ID
    method: rfe
