dag:
  sources:
  - id: s0
    table: interaction
  - id: s1
    table: user
  - id: s2
    table: item
  ops:
  - id: o1
    op: JoinTable
    prev:
    - s0
    - s2
    - s1
    params:
      user_col: user_id
      item_col: item_id
      how: left
      method: rec
  - id: o2
    op: DropColumns
    prev:
    - o1
    params:
      cols:
      - user_zip_code
      - item_title
  - id: o3
    op: FilterSample
    prev:
    - o2
    params:
      subset:
      - user_id
      - item_id
      - rating
  - id: o4
    op: FilterKCore
    prev:
    - o3
    params:
      user_col: user_id
      item_col: item_id
      k: 5
  - id: o5
    op: CreateSequence
    prev:
    - o4
    params:
      user_col: user_id
      item_col: item_id
      time_col: timestamp
      seq_col: item_id_seq
      max_len: 20
  - id: o6
    op: SampleNegative
    prev:
    - o5
    params:
      user_col: user_id
      item_col: item_id
      target_col: rating
      n_negatives: 1
      positive_label: 1
      negative_label: 0
      seed: 42
  - id: o7
    op: FilterSample
    prev:
    - o6
    params:
      subset:
      - rating
  train:
    prev:
    - o7
