pipeline:
- op: ExtractDateTimeFeature
  target: both
  params:
    cols:
    - TransactionDT
    features:
    - day_of_week
    - hour_of_day
    drop_original: true
- op: TransformPower
  target: both
  params:
    cols:
    - TransactionAmt
    output_cols:
    - TransactionAmt_log
    method: log
- op: RenameColumn
  target: both
  params:
    rename_map:
      TransactionAmt: trans_amt
- op: CustomProcess
  target: both
  params:
    cols:
    - card1
    - card2
    - card3
    - card5
    - addr1
    - addr2
    - P_emaildomain
    - R_emaildomain
    mode: frequency_encode
- op: HashEncode
  target: both
  params:
    cols:
    - card1
    n_buckets: 4096
- op: CustomProcess
  target: both
  params:
    threshold: 0.9
    mode: drop_high_null
- op: DropColumns
  target: both
  params:
    cols:
    - TransactionID
- op: LabelEncode
  target: both
- op: HandleMV
  target: both
  params:
    method: median
