pipeline:
- op: JoinTable
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    user_df: $user_df
    item_df: $item_df
    how: left
    method: rec
- op: DropColumns
  target: interaction
  params:
    cols:
    - time
    - date
    - play_duration
    - video_duration
- op: FilterSample
  target: interaction
  params:
    subset:
    - user_id
    - item_id
    - watch_ratio
- op: HandleMV
  target: interaction
  params:
    cols:
    - item_video_duration
    - item_video_width
    - item_video_height
    method: median
- op: FilterKCore
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    k: 5
- op: CreateSequence
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    time_col: timestamp
    seq_col: item_id_seq
    max_len: 20
- op: SampleNegative
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    target_col: watch_ratio
    n_negatives: 1
    positive_label: 1
    negative_label: 0
    seed: 42
- op: FilterSample
  target: interaction
  params:
    subset:
    - watch_ratio
