pipeline:
- op: ExtractDateTimeFeature
  target: train
  params:
    cols:
    - dteday
    features:
    - year
    - month
    - day
    - dayofweek
    - quarter
    - is_weekend
    - dayofyear
    drop_original: true
- op: ExtractDateTimeFeature
  target: day
  params:
    cols:
    - dteday
    features:
    - dayofweek
    - is_weekend
    - dayofyear
    drop_original: true
- op: CustomProcess
  target: day
  params:
    cols:
    - casual
    - registered
    - cnt
    mode: drop_columns
- op: CreateFeature
  target: train
  params:
    source_cols:
    - atemp
    - temp
    output_col: temp_diff
    method: diff
- op: TransformPower
  target: train
  params:
    cols:
    - hum
    - windspeed
    output_cols:
    - hum_log
    - windspeed_log
    method: log
- op: JoinTable
  target: train
  params:
    aux_df: $day
    key_col: weekday
    prefix: DAY
    max_cols: 10
    method: agg
- op: CreateLagFeature
  target: train
  params:
    target_col: cnt
    lags:
    - 1
    - 24
    - 168
    time_col: _sort_idx
- op: CreateRollingFeature
  target: train
  params:
    target_col: cnt
    windows:
    - 24
    - 168
    aggs:
    - mean
    - std
    time_col: _sort_idx
- op: CustomProcess
  target: train
  params:
    threshold: 0.7
    mode: drop_high_null
- op: CustomProcess
  target: train
  params:
    cols:
    - casual
    - registered
    mode: drop_columns
- op: LabelEncode
  target: train
- op: HandleMV
  target: train
  params:
    method: median
