pipeline:
- op: ExtractDateTimeFeature
  target: train
  params:
    cols:
    - _hour_ts
    features:
    - month
    - day
    - dayofweek
    - is_weekend
    - dayofyear
    drop_original: true
- op: CreateLagFeature
  target: train
  params:
    target_col: trip_count
    lags:
    - 1
    - 2
    - 3
    - 24
    - 168
    group_cols:
    - PULocationID
    time_col: _hour_idx
- op: CreateRollingFeature
  target: train
  params:
    target_col: trip_count
    windows:
    - 6
    - 24
    - 168
    aggs:
    - mean
    - std
    - min
    - max
    group_cols:
    - PULocationID
    time_col: _hour_idx
- op: CustomProcess
  target: train
  params:
    threshold: 0.7
    mode: drop_high_null
- op: HandleMV
  target: train
  params:
    method: median
- op: TransformPower
  target: train
  params:
    cols:
    - trip_distance_mean
    - trip_distance_sum
    - fare_amount_mean
    - fare_amount_sum
    output_distribution: normal
    method: quantile
- op: SortRows
  target: train
  params:
    by:
    - PULocationID
    - _hour_idx
    ascending: true
