dag:
  sources:
  - id: s0
    table: main
  ops:
  - id: o1
    op: ExtractDateTimeFeature
    prev:
    - s0
    params:
      cols:
      - _hour_ts
      features:
      - month
      - day
      - dayofweek
      - is_weekend
      - dayofyear
      drop_original: true
  - id: o2
    op: CreateLagFeature
    prev:
    - o1
    params:
      target_col: trip_count
      lags:
      - 1
      - 2
      - 3
      - 24
      - 168
      group_cols:
      - PULocationID
      time_col: _hour_idx
  - id: o3
    op: CreateRollingFeature
    prev:
    - o2
    params:
      target_col: trip_count
      windows:
      - 6
      - 24
      - 168
      aggs:
      - mean
      - std
      - min
      - max
      group_cols:
      - PULocationID
      time_col: _hour_idx
  - id: o4
    op: CustomProcess
    prev:
    - o3
    params:
      threshold: 0.7
      mode: drop_high_null
  - id: o5
    op: HandleMV
    prev:
    - o4
    params:
      method: median
  - id: o6
    op: TransformPower
    prev:
    - o5
    params:
      cols:
      - trip_distance_mean
      - trip_distance_sum
      - fare_amount_mean
      - fare_amount_sum
      output_distribution: normal
      method: quantile
  - id: o7
    op: SortRows
    prev:
    - o6
    params:
      by:
      - PULocationID
      - _hour_idx
      ascending: true
  train:
    prev:
    - o7
