pipeline:
- op: JoinTable
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    user_df: $user_df
    item_df: $item_df
    how: left
    method: rec
- op: HandleMV
  target: interaction
  params:
    cols:
    - vote
    - item_price
    method: median
- op: FilterKCore
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    k: 2
- op: CreateSequence
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    time_col: timestamp
    seq_col: item_id_seq
    max_len: 20
