pipeline:
- op: JoinTable
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    user_df: $user_df
    item_df: $item_df
    how: left
    method: rec
- op: CustomProcess
  target: interaction
  params:
    cols:
    - user_name
    - item_name
    mode: drop_columns
- op: FilterSample
  target: interaction
  params:
    subset:
    - user_id
    - item_id
    - rating
- op: HandleMV
  target: interaction
  params:
    cols:
    - vote
    - item_price
    method: median
- op: CreateSequence
  target: interaction
  params:
    user_col: user_id
    item_col: item_id
    time_col: timestamp
    seq_col: item_id_seq
    max_len: 20
