model: LightGBM
model_params:
  task: binary
  seed: 42
  n_estimators: 2000
  learning_rate: 0.05
  num_leaves: 31
  max_depth: 6
  min_child_samples: 30
  colsample_bytree: 0.8
  subsample: 0.8
  reg_alpha: 0.1
  reg_lambda: 0.1

train:
  val_ratio: 0.2
  metrics: [auc]
  seed: 42

model_options:
  LightGBM: {}
  MLP:
    model_params:
      task: binary
      seed: 42
      epochs: 10
      batch_size: 256
      lr: 0.001
      weight_decay: 0.00001
      hidden_units: [128, 64]
      dropout: 0.1
      device: cpu
    train: &polish_bankruptcy_tabular_train
      val_ratio: 0.2
      metrics: [auc]
      seed: 42
  TabTransformer: &polish_bankruptcy_tab_transformer
    model_params:
      task: binary
      seed: 42
      epochs: 10
      batch_size: 256
      lr: 0.001
      weight_decay: 0.00001
      d_model: 32
      nhead: 4
      num_layers: 2
      dim_feedforward: 64
      dropout: 0.1
      device: cpu
    train: *polish_bankruptcy_tabular_train
  FTTransformer: *polish_bankruptcy_tab_transformer
  SAINT:
    model_params:
      task: binary
      seed: 42
      epochs: 10
      batch_size: 256
      lr: 0.001
      weight_decay: 0.00001
      d_model: 32
      nhead: 4
      num_layers: 2
      dim_feedforward: 64
      dropout: 0.1
      row_attention: false
      device: cpu
    train: *polish_bankruptcy_tabular_train
