pipeline:
- op: ConcatTable
  target: year1
  params:
    other_dfs:
    - $year2
    - $year3
    - $year4
    axis: vertical
    fill_missing: true
- op: TransformPower
  target: train
  params:
    cols:
    - Attr1
    - Attr9
    output_cols:
    - ATTR1_LOG
    - ATTR9_LOG
    method: log
- op: CreatePolynomialFeature
  target: train
  params:
    cols:
    - Attr1
    - Attr3
    - Attr6
    - Attr9
    degree: 2
    interaction_only: true
- op: JoinTable
  target: train
  params:
    aux_df: $year1
    key_col: _join_key
    prefix: ALLYEARS
    max_cols: 50
    method: agg
- op: DropColumns
  target: train
  params:
    cols:
    - _join_key
- op: CustomProcess
  target: train
  params:
    threshold: 0.7
    mode: drop_high_null
- op: LabelEncode
  target: train
- op: HandleMV
  target: train
  params:
    cols:
    - Attr1
    - Attr3
    - Attr6
    - Attr9
    max_iter: 5
    method: iterative
- op: HandleMV
  target: train
  params:
    method: median
- op: Oversample
  target: train
  params:
    target_col: $target_col
    n_neighbors: 5
    method: adasyn
